export const ActionTypes={
    SET_PRODUCTS:"SET_PRODUCT",
    SELECTED_PRODUCT:"SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
    ADD_PRODUCT_TO_STORE:"ADD_PRODUCT_TO_STORE"
}